### ISSUE TITLE
Python 3.3 installation error

### ISSUE THREAD

**Issue by zopyx** [fschulze/mr.developer#131]
I tried to install a buildout using zc.buildout 2.1 and mr.developer 1.26 under Python 3.3. This fails:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/ajung/sandboxes/pp.server/lib/python3.3/site-packages/setuptools/command/easy_install.py", line 1992, in main
    with_ei_usage(lambda:
  File "/home/ajung/sandboxes/pp.server/lib/python3.3/site-packages/setuptools/command/easy_install.py", line 1979, in with_ei_usage
    return f()
  File "/home/ajung/sandboxes/pp.server/lib/python3.3/site-packages/setuptools/command/easy_install.py", line 1996, in <lambda>
    distclass=DistributionWithoutHelpCommands, **kw
  File "/opt/buildout.python/parts/opt/lib/python3.3/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/opt/buildout.python/parts/opt/lib/python3.3/distutils/dist.py", line 929, in run_commands
    self.run_command(cmd)
  File "/opt/buildout.python/parts/opt/lib/python3.3/distutils/dist.py", line 948, in run_command
    cmd_obj.run()
  File "/home/ajung/sandboxes/pp.server/lib/python3.3/site-packages/setuptools/command/easy_install.py", line 380, in run
    self.easy_install(spec, not self.no_deps)
  File "/home/ajung/sandboxes/pp.server/lib/python3.3/site-packages/setuptools/command/easy_install.py", line 604, in easy_install
    return self.install_item(None, spec, tmpdir, deps, True)
  File "/home/ajung/sandboxes/pp.server/lib/python3.3/site-packages/setuptools/command/easy_install.py", line 653, in install_item
    dists = self.install_eggs(spec, download, tmpdir)
  File "/home/ajung/sandboxes/pp.server/lib/python3.3/site-packages/setuptools/command/easy_install.py", line 849, in install_eggs
    return self.build_and_install(setup_script, setup_base)
  File "/home/ajung/sandboxes/pp.server/lib/python3.3/site-packages/setuptools/command/easy_install.py", line 1130, in build_and_install
    self.run_setup(setup_script, setup_base, args)
  File "/home/ajung/sandboxes/pp.server/lib/python3.3/site-packages/setuptools/command/easy_install.py", line 1115, in run_setup
    run_setup(setup_script, args)
  File "/home/ajung/sandboxes/pp.server/lib/python3.3/site-packages/setuptools/sandbox.py", line 69, in run_setup
    lambda: execfile(
  File "/home/ajung/sandboxes/pp.server/lib/python3.3/site-packages/setuptools/sandbox.py", line 120, in run
    return func()
  File "/home/ajung/sandboxes/pp.server/lib/python3.3/site-packages/setuptools/sandbox.py", line 71, in <lambda>
    {'**file**':setup_script, '**name**':'**main**'}
  File "/home/ajung/sandboxes/pp.server/lib/python3.3/site-packages/setuptools/compat.py", line 92, in execfile
    exec_(compile(source, fn, 'exec'), globs, locs)
  File "setup.py", line 37, in <module>
  File "/home/ajung/sandboxes/pp.server/lib/python3.3/encodings/ascii.py", line 27, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc5 in position 3310: ordinal not in range(128)
An error occurred when trying to install mr.developer 1.26. Look above this message for any errors that were output by easy_install.
While:
  Installing.
  Loading extensions.
  Getting distribution for 'mr.developer'.
Error: Couldn't install: mr.developer 1.26

**Comment by reinout** [comment]
This one can probably be closed?
