### ISSUE TITLE
Passing assigments to buildout commands fails when mr.developer is in use.

### ISSUE THREAD

**Issue by mvaled** [fschulze/mr.developer#151]
I have a buildout like this:

    [buildout]
    extensions += mr.developer

    always-checkout = force
    sources = sources
    sources-dir = src/staging
    auto-checkout = *

    rev=origin/master

    ...

    [sources]
    some.package = git git@gitlab.example.com:some-package.git rev=${buildout:rev}
    # many other packages that use the same rev=${buildout:rev}

When doing a pre-release check I want to pass the `rev` assignment to test the branch I'm checking to be merge to the stable branch: `bin/buildout rev=origin/stage install`.  But then mr.developer fails with:

    Traceback (most recent call last):
      File "/home/manu/.local/lib/python2.7/site-packages/zc/buildout/buildout.py", line 1942, in main
	getattr(buildout, command)(args)
      File "/home/manu/.local/lib/python2.7/site-packages/zc/buildout/buildout.py", line 463, in install
	self._load_extensions()
      File "/home/manu/.local/lib/python2.7/site-packages/zc/buildout/buildout.py", line 998, in _load_extensions
	ep.load()(self)
      File "/home/manu/.buildout/eggs/mr.developer-1.21-py2.7.egg/mr/developer/extension.py", line 246, in extension
	return Extension(buildout)()
      File "/home/manu/.buildout/eggs/mr.developer-1.21-py2.7.egg/mr/developer/extension.py", line 242, in __call__
	config.save()
      File "/home/manu/.buildout/eggs/mr.developer-1.21-py2.7.egg/mr/developer/common.py", line 402, in save
	options, settings, args = parse_buildout_args(self.buildout_args[1:])
      File "/home/manu/.buildout/eggs/mr.developer-1.21-py2.7.egg/mr/developer/common.py", line 329, in parse_buildout_args
	raise ValueError('Invalid option:', option)
    ValueError: ('Invalid option:', 'rev')

Running buildout like this `bin/buildout buildout:rev=origin/stage install` works ok.

**Comment by reinout** [comment]
@mauritsvanrees: looks like this issue can be closed, right?

**Comment by mauritsvanrees** [comment]
Yes, indeed, thanks.
