### ISSUE TITLE
bin/develop without params throws traceback

### ISSUE THREAD

**Issue by fredvd** [fschulze/mr.developer#196]
Happens in 2.0.0 on python 3.7, OS X 10.14, running:

> bin/develop

without parameters throws a traceback:
```fred@Tycho:api (git:voltodemo-develop+?) $ bin/develop
Setting socket time out to 10 seconds.
Traceback (most recent call last):
  File "bin/develop", line 13, in <module>
    sys.exit(mr.developer.develop.develop())
  File "/Users/fred/.buildout/eggs/mr.developer-2.0.0-py3.7.egg/mr/developer/develop.py", line 103, in __call__
    args.func(args)
AttributeError: 'Namespace' object has no attribute 'func'
```

where 1.x (1.38 here) on Python 2.7 shows usage: 

```
(git:master+?) $ bin/develop
usage: develop [-h] [-v]  ...
develop: error: too few arguments
```

**Comment by fschulze** [comment]
I think this was fixed at some point. I use mr.developer almost exclusively with Python 3.x now and never encountered this. If this is still an issue, please feel free to reopen with current infos.
