### ISSUE TITLE
Buildout can't pull default branch if named "main"

### ISSUE THREAD

**Issue by agitator** [fschulze/mr.developer#208]
```
mr.developer: No such branch 'master'
mr.developer: Updated 'bda.plone.wallee' with git.
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/Users/peter/.pyenv/versions/3.8.6/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/Users/peter/.pyenv/versions/3.8.6/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/peter/workspace/bda.plone.shop/eggs/mr.developer-2.0.1-py3.8.egg/mr/developer/common.py", line 181, in worker
    for lvl, msg in wc._output:
ValueError: too many values to unpack (expected 2)
```

Configuring the `branch=main` within buildout "solves" the problem

**Comment by icemac** [comment]
As `main` is much more used nowadays, is there a chance to make it the default or have an option to define the default branch name?
